# install recipe
# [Mikunopop Project]
# 
# $URL: svn+ssh://ryo@aquahill.net/home/ryo/svn/fumi2/trunk/install/recipe.yml $
# $Id: recipe.yml 18 2008-07-13 15:25:55Z ryo $

base:
  base: /web/mikunopop
  recipe:
    - core
    - media

